project_name: "FlightDelayPrediction"
version: "1.0.0"

system:
  device: "cpu"

paths:
  state_dir: "state/models"
  model_file: "gnn_flight_delay.pth"
  scaler_file: "scaler.pkl"
  airport_encoder: "airport_encoder.pkl"
  carrier_encoder: "carrier_encoder.pkl"

kafka:
  bootstrap_servers: ["localhost:19092","kafka:9092"]
  topic_input: "flight_data_stream"
  topic_output: "flight_predictions"
  consumer_group: "flight_gnn_group"

model:
  input_edge_feats: 10
  hidden_dim: 64
  heads: 2
  threshold: 0.5
  epochs: 1000

cassandra:
  hosts: ["localhost"]
  port: 9042
  keyspace: "flight_ks"
  table_training: "training_data"

spark:
  checkpoint_location: ["state/spark/checkpoint_inference", "state/spark/checkpoint_archiving"]